import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/ProductDashboard.module.css";
import { useState, useEffect } from "react";

const Products = () => {
  const [products, setProducts] = useState([]);
  const [categoryFilter, setCategoryFilter] = useState(null); //"Food", "Technology"
  const [shouldReload, setShouldReload] = useState(true);

  const handleSubmit = async (event) => {
    try {
      event.preventDefault();
      const data = Object.fromEntries(new FormData(event.target));

      const newProduct = {
        name: data.name,
        category: data.category,
        details: data.details,
      };
      console.log(data);

      const options = {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newProduct),
      };
      const response = await fetch("/api/products/", options);
      const result = await response.json();
      setShouldReload(true);
      /*   alert(`Is this your full name: ${result.data}`); */
    } catch (error) {
      console.log(error);
      alert(error.message);
    }
  };

  useEffect(() => {
    const getProducts = async () => {
      try {
        const url = categoryFilter
          ? `/api/products?category=${categoryFilter}`
          : "/api/products";
        const response = await fetch(url);
        if (response.ok) {
          const data = await response.json();
          setProducts(data);
          setShouldReload(false);
        } else {
          throw new Error(
            `Fetch fehlgeschlagen mit Status: ${response.status}`
          );
        }
      } catch (error) {
        console.log(error);
        alert(error.message);
      }
    };
    getProducts();
  }, [categoryFilter, shouldReload]);

  const deleteProduct = async (id) => {
    try {
      const response = await fetch(`/api/products/${id}`, {
        method: "DELETE",
      });
      setShouldReload(true);
    } catch (error) {
      console.log(error);
      alert(error.message);
    }
  };

  return (
    <>
      <Head>
        <title>Product Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="test">Products Dashboard</h1>
        <h3>Add new Product</h3>

        <select
          onChange={(event) => {
            if (event.target.value === "all") {
              setCategoryFilter(null);
            } else {
              setCategoryFilter(event.target.value);
            }
          }}
        >
          <option value="all">Alle</option>
          <option value="Food">Food</option>
          <option value="Technology">Technology</option>
        </select>
        <p>{categoryFilter}</p>
        <ul className={styles["product-list"]}>
          {products.map((product) => {
            return (
              <li key={product._id}>
                <Link href={`/products/${product._id}`}>{product.name}</Link>
                <button onClick={() => deleteProduct(product._id)}>
                  DELETE
                </button>
              </li>
            );
          })}
        </ul>
        <form onSubmit={handleSubmit}>
          <label>
            Name:
            <input type="text" id="name" name="name" />
          </label>
          <label>
            Category:
            <input type="text" id="category" name="category" />
          </label>
          <label>
            Detail:
            <input type="text" id="detail" name="detail" />
            <button type="submit">Submit</button>
          </label>
        </form>
      </div>
    </>
  );
};

export default Products;
